[package]
name = "clog"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
base64 = "0.22.1"
chrono = "0.4.41"
color-eyre = "0.6.4"
crossterm = "0.29.0"
getrandom = "0.3.2"
linked-hash-map = "0.5.6"
pbkdf2 = "0.12.2"
ratatui = "0.29.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sha2 = "0.10.9"
